### ISSUE TITLE
Is this dataset suitable for benchmarking visual slam?

### ISSUE THREAD

**Issue by hitdshu** [valeoai/WoodScape#25]
Hi, 

Thanks for your kindness in sharing the data. The paper says, it contains several videos for benchmarking visual odometry/slam. However, I could not find suitable video data in your current description. Am I missing something? 

Deshun

**Comment by ctwitt** [comment]
Hello Deshun,
you are right. The paper says that there will be suitable data for visual odometry/SLAM, but it is not included in the current data set of images. Unfortunately, we could not release the original planned data set for this task due to data protection restrictions. We are hardly working on finding a solution for that to keep our promises, like doing recordings in our own test area. It might take another two months. We will update the dataset as soon as possible.

Best regards
Christian

**Comment by hitdshu** [comment]
Your reply is really appreciated. Thanks very much for your hard work in this dataset. 

I just want to make sure that I didn't miss anything. Thanks for your kindness in sharing the data.

Best,
Deshun
