### ISSUE TITLE
Depth ground-truth missing

### ISSUE THREAD

**Issue by WeihengXia0123** [valeoai/WoodScape#31]
Hi guys,

Thanks for releasing the dataset. It's very useful for my research with fisheye cameras.

I'm trying to implement your paper `FisheyeDistanceNet` on depth estimation with Woodscape Dataset, but I didn't find Fisheye Images' ground-truth depth map or sparse lidar ground-truth in the current dataset.

Will you release the GT for depth soon?

Best,
Weiheng

**Comment by ctwitt** [comment]
Hello Weiheng,

you are right. The paper says that there will be suitable data for depth estimation, but it is not included in the current data set of images. Unfortunately, we could not release the original planned data set for this task due to data protection restrictions. We are hardly working on finding a solution for that to keep our promises, like doing recordings in our own test area. It might take another two months. We will update the dataset as soon as possible.

Best regards
Christian

**Comment by XinchaoGou** [comment]
> Hello Weiheng,
> 
> you are right. The paper says that there will be suitable data for depth estimation, but it is not included in the current data set of images. Unfortunately, we could not release the original planned data set for this task due to data protection restrictions. We are hardly working on finding a solution for that to keep our promises, like doing recordings in our own test area. It might take another two months. We will update the dataset as soon as possible.
> 
> Best regards
> Christian

Hi Christian

Thanks for the WoodScape dataset! 
However, I had this failure as shown in the picture below when I tried to download the "rgb_images.zip" from google drive.
Is this due to the same "data protection" problem as you mentioned?
![image](https://user-images.githubusercontent.com/35408641/118909288-62731500-b955-11eb-8e7b-0dc6bf20c0c3.png)


Best regards,
Xinchao

**Comment by Xpangz** [comment]
> Hello Weiheng,
> 
> you are right. The paper says that there will be suitable data for depth estimation, but it is not included in the current data set of images. Unfortunately, we could not release the original planned data set for this task due to data protection restrictions. We are hardly working on finding a solution for that to keep our promises, like doing recordings in our own test area. It might take another two months. We will update the dataset as soon as possible.
> 
> Best regards Christian

Hi, it is November now. Have you found a solution to update the dataset about depth estimation?

**Comment by 100daggers** [comment]
@Xpangz 

Hi , Thank youso much for your paper.
 Is there a chance that we will recieve the depth estimation lables?

**Comment by Xpangz** [comment]
> @Xpangz
> 
> Hi , Thank youso much for your paper. Is there a chance that we will recieve the depth estimation lables?

I'm not the paper's author, and I am also waiting for the estimation labels  (′⌒`)

**Comment by zcyyyy24** [comment]
> Hello Weiheng,
> 
> you are right. The paper says that there will be suitable data for depth estimation, but it is not included in the current data set of images. Unfortunately, we could not release the original planned data set for this task due to data protection restrictions. We are hardly working on finding a solution for that to keep our promises, like doing recordings in our own test area. It might take another two months. We will update the dataset as soon as possible.
> 
> Best regards Christian

Hi, over the past three years, the depth ground truth was still not released.
Is there any access to get depth labels? I really need it to complish my academic research.
Best regards
Congyu Zhang
