### ISSUE TITLE
cylindrical to fisheye 

### ISSUE THREAD

**Issue by tfzhou** [valeoai/WoodScape#39]
Hi, thanks for contributing the dataset and sharing the utility codes.

The fisheye->cylindrical code works well, however, is it possible to convert the cylindrical image back to the fisheye image?

I have tried to project cylindrical cam to fisheye cam, but the conversion is super slow and the results are not good now. 

I will appreciate any ideas regarding this issue. Thanks.

![01410_MVR](https://user-images.githubusercontent.com/5791480/119597754-f1fb4680-bde1-11eb-9869-d5b6ed237c4d.png)
![01445_FV](https://user-images.githubusercontent.com/5791480/119597800-03dce980-bde2-11eb-9487-76544e4a55f8.png)

**Comment by hamza9305** [comment]
Hey Tianfei Zhou,

Where did you find the code which converts fisheye to cylindrical image?

Regards,
Hamza

**Comment by ctwitt** [comment]
Hello Tianfei Zhou and Hamza,

in theory it is possible to transform cylindrical images into fisheye images. However, this is only possible/useful if the viewport of the cylindrical image is large enough to cover the viewport of the fisheye image. So I'd not recommend doing it.

The transformation might be slow, because you use a non-optimized version for the inverse projection. As there are only about 20 different intrinsics, you could cache the conversion maps after generation to speed up processing multiple images.

The code for the transformation is not available for this explicit case, but it can be realized based on the existing [example](https://github.com/valeoai/WoodScape/blob/master/scripts/calibration/example.py).

Best regards,
Christian

**Comment by yunhaoqiao** [comment]
Hello Brothers, 
How is the result now? Is there a way to improve  @tfzhou 

Regards，
Yunhao
